project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "!/unbelievable/"
    - "!/prato2023/"

website:
  title: "Rob J Hyndman"
  site-url: "https://robjhyndman.com"
  open-graph: true
  twitter-card:
    creator: "@robjhyndman"
  navbar:
    background: "#234460"
    left:
      - href: hyndsight/index.qmd
        text: Hyndsight blog
      - href: publications/index.qmd
        text: Publications
      - href: software/index.qmd
        text: Software
      - href: seminars/index.qmd
        text: Seminars
      - href: teaching/index.qmd
        text: Teaching
      - href: research-team/index.qmd
        text: Research Team
      - href: about/index.qmd
        text: About
  page-footer:
    left: "© 1993-2023, Rob J Hyndman <a rel='me' href='https://aus.social/@robjhyndman'></a>"
    right:
      - text: Subscribe
        href: /subscribe.html
      - icon: rss
        href: https://robjhyndman.com/index.xml
    background: "#234460"

date-format: "D MMMM YYYY"
freeze: true

format:
  html:
    theme:
      - tango
      - rjh.scss
    toc: true
    mainfont: "Merriweather, Georgia, serif"
    html-math-method: katex
    include-in-header:
      file: header.html
