project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "!/unbelievable/"

website:
  title: "Rob J Hyndman"
  site-url: "https://robjhyndman.com"
  navbar:
    background: "#536878"
    left:
      - href: hyndsight/index.qmd
        text: Hyndsight blog
      - href: publications/index.qmd
        text: Publications
      - href: software/index.qmd
        text: Software
      - href: seminars/index.qmd
        text: Seminars
      - href: teaching/index.qmd
        text: Teaching
      - href: research-team/index.qmd
        text: Research Team
      - href: about/index.qmd
        text: About
  page-footer:
    left: "© 1993-2022, Rob J Hyndman"
    right:
      - text: Subscribe
        href: /subscribe.html
      - icon: rss
        href: https://robjhyndman.com/index.xml
      - icon: github
        href: https://github.com/robjhyndman
      - icon: mastodon
        href: https://aus.social/@robjhyndman
    background: "#536878"

date-format: "D MMMM YYYY"
freeze: true

format:
  html:
    theme: tango
    css: styles.css
    toc: true
    html-math-method: katex
    include-in-header:
      file: header.html
