project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "!/unbelievable/"
    - "!/prato2023/"

website:
  title: "Rob J Hyndman"
  site-url: "https://robjhyndman.com"
  open-graph: true
  navbar:
    background: "#234460"
    left:
      - href: hyndsight/index.qmd
        text: Hyndsight blog
      - href: publications/index.qmd
        text: Publications
      - href: software/index.qmd
        text: Software
      - href: seminars/index.qmd
        text: Seminars
      - href: teaching/index.qmd
        text: Teaching
      - href: research-team/index.qmd
        text: Research Team
      - href: about/index.qmd
        text: About
  page-footer:
    left: "&copy; 1993-[]{#current-year} Rob J Hyndman <a rel='me' href='https://aus.social/@robjhyndman'></a>"
    right:
      - text: Subscribe
        href: /subscribe.html
      - icon: rss
        href: https://robjhyndman.com/index.xml
    background: "#234460"

date-format: "D MMMM YYYY"
freeze: true

format:
  html:
    theme:
      light:
        - tango
        - rjh.scss
    toc: true
    mainfont: "Merriweather, Georgia, serif"
    html-math-method: katex
    code-link: true
    fig-responsive: true
    include-in-header:
      file: header.html
    include-after-body:
      - text: |
          <script>
            document.getElementById('current-year').textContent = new Date().getFullYear();
          </script>
