---
pagetitle: "Rob J Hyndman - Software"
freeze: false
toc: true
toc-depth: 2
---

```{r}
#| label: functions
#| include: false
library(tidyverse)
source(here::here("software/software_functions.R"))
```

```{css}
/*| label: h1_heading */
/*| echo: false */
h1 {
  padding-bottom: 0px;
  margin-bottom: 0px;
}
```

#### [Repository Dashboard](https://pkg.robjhyndman.com/gh-dashboard/){.badge .badge-large .badge-blue} [R Universe](https://robjhyndman.r-universe.dev/){.badge .badge-large .badge-blue}

# CRAN task views

* [**Time Series**](https://cran.r-project.org/view=TimeSeries)
* [**Anomaly Detection**](https://cran.r-project.org/view=AnomalyDetection)

# Selected R packages

```{r}
#| label: r_packages
#| echo: false
#| output: asis
#| warning: false
#| message: false
packages <- rjh_packages() |>
  suppressMessages() |>
  suppressWarnings()
sections <- unique(packages$section)
for (i in seq_along(sections)) {
  packages |>
    filter(section == sections[i]) %>%
    package_table()
}
```

# Quarto extensions

## Monash University templates

```{r}
#| label: quarto_extensions
#| output: asis
#| echo: false
extensions <- tibble::tribble(
  ~repo          , ~description                                                                                         ,
  "exam"         , "Create an exam for Monash Business School"                                                          ,
  "letter"       , "Create a letter on Monash Business School letterhead"                                               ,
  "memo"         , "Create a memo with optional Monash Business School branding"                                        ,
  "presentation" , "Create a Monash University themed presentation using either Beamer or RevealJS"                     ,
  "report"       , "Create a Monash Business School consulting report"                                                  ,
  "thesis"       , "Create a Monash University thesis"                                                                  ,
  "unit"         , "Create a unit website for Monash Business School"                                                   ,
  "workingpaper" , "Create a working paper for the Department of Econometrics & Business Statistics, Monash University" ,
)
for (i in seq_len(nrow(extensions))) {
  quarto_extension(extensions$repo[i], extensions$description[i])
}
```

## Other templates

```{r}
#| label: other_extensions
#| output: asis
#| echo: false
quarto_extension(
  "ims-journals",
  "Create a submission for an IMS journal such as <em>Statistical Science</em> or <em>Annals of Applied Statistics</em>"
)
```
