---
pagetitle: "Rob J Hyndman - Teaching"
---

# ETC3550: Applied Forecasting for Business and Economics

Reliable forecasts of business and economic variables must often be obtained against a backdrop of structural change in markets and the economy. This unit introduces methods suitable for forecasting in these circumstances including the decomposition of time series, exponential smoothing methods, ARIMA modelling, and regression with auto-correlated disturbances. Students can expect to enhance their computer skills with exercises using R.

**[Handbook entry](https://handbook.monash.edu/current/units/ETC3550)**

**Textbook:** [*Forecasting: Principles and Practice*, Hyndman & Athanasopoulos (3rd ed., 2020)](https://OTexts.org/fpp3/)

[**Slides**](https://github.com/robjhyndman/ETC3550Slides/releases/tag/2022)

* * *

# Tidy time series & forecasting in R

*This is a 2-day workshop held no more than once per year.*

**Day 1**: We look at the tsibble data structure for flexibly managing collections of related time series. We look at how to do data wrangling, data visualizations and exploratory data analysis. We explore feature-based methods to explore time series data in high dimensions. A similar feature-based approach can be used to identify anomalous time series within a collection of time series, or to cluster or classify time series. Primary packages for day 1 are [tsibble](https://cran.r-project.org/package=tsibble), [lubridate](https://cran.r-project.org/package=lubridate) and [feasts](https://cran.r-project.org/package=feasts) (along with the [tidyverse](http://tidyverse.org) of course).

**Day 2** is about forecasting. We look at some classical time series models and how they are automated in the [fable](https://cran.r-project.org/package=fable) package. We look at creating ensemble forecasts and hybrid forecasts, as well as some new forecasting methods that have performed well in large-scale forecasting competitions. Finally, we look at forecast reconciliation, allowing millions of time series to be forecast in a relatively short time while accounting for constraints on how the series are related.

[**More information . . .**](http://robjhyndman.com/workshop2020/)

* * *
