---
title: "About me"
---

::: {.columns}
::::: {.column width="30%"}
<div class="badge-stack">
[{{< fa file-pdf >}} Curriculum Vitae](https://cdn.jsdelivr.net/gh/robjhyndman/CV@main/RobHyndmanCV.pdf){.badge .badge-large}\
[{{< fa brands github >}} GitHub](https://github.com/robjhyndman){.badge .badge-large}\
[{{< fa brands wikipedia-w >}} Wikipedia](http://en.wikipedia.org/wiki/Rob_J._Hyndman){.badge .badge-large}
</div>
:::::

::::: {.column width="30%"}
<div class="badge-stack">
[{{< ai google-scholar >}} Google Scholar](https://scholar.google.com/citations?user=vamErfkAAAAJ){.badge .badge-large}\
[{{< ai semantic-scholar >}} Semantic Scholar](https://www.semanticscholar.org/author/R.-Hyndman/145211352){.badge .badge-large}\
[{{< ai orcid >}} ORCID](https://orcid.org/0000-0002-2140-5352){.badge .badge-large}
</div>
:::::

::::: {.column width="30%"}
<div class="badge-stack">
[{{< ai scopus >}} Scopus](https://www.scopus.com/authid/detail.uri?authorId=7006914313){.badge .badge-large}\
[{{< ai arxiv >}} arXiv](https://arxiv.org/a/hyndman_r_1.html){.badge .badge-large}\
[{{< fa lightbulb >}} RePEc](http://ideas.repec.org/e/phy3.html){.badge .badge-large}
</div>
:::::
:::

## Bio

The following bio and [**this photo**](/img/RJH_AAS.jpg) may be used in media releases without further permission.

<div class="quote-card">

**Rob J Hyndman** <span style="font-size: 10pt;">FAA FASSA</span> holds the position of Vice-Chancellor's Distinguished Professor of Statistics in the [Department of Econometrics and Business Statistics](https://monash.edu/business/ebs) at [Monash University](https://www.monash.edu), and is an elected Fellow of both the [Australian Academy of Science](https://www.science.org.au/profile/rob-hyndman) and the [Academy of Social Sciences in Australia](https://socialsciences.org.au/academy-fellow/?sId=0032v00003JxrvjAAB).
He is the author of over 230 research papers and 6 books in statistical science.
In 2007, he received the [Moran medal](https://www.science.org.au/past-winners/2007-awardees#moran) from the Australian Academy of Science for his contributions to statistical research, especially in the area of statistical forecasting.
In 2021, he received the [Pitman medal](https://www.statsoc.org.au/Pitman-Medal-Recipients) from the Statistical Society of Australia.
For over 40 years, Rob has maintained an active consulting practice, assisting hundreds of companies and organizations around the world.
He has won awards for his research, teaching, consulting and graduate supervision.

</div>

## Address

**Mail:** [Department of Econometrics & Business Statistics](https://monash.edu/business/ebs), [Monash University](https://monash.edu/), Clayton VIC 3800, Australia.

**Office:** Room 355, 29 Ancora Imparo Way, Clayton campus, [Monash University](https://monash.edu/), VIC 3800, Australia.

<div class="map-embed">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1573.8494801911916!2d145.13333138705417!3d-37.91409860115737!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad66acc44ceea8d%3A0xa8874d62c042a30f!2s29%20Ancora%20Imparo%20Wy%2C%20Clayton%20VIC%203168!5e0!3m2!1sen!2sau!4v1649573729090!5m2!1sen!2sau"></iframe>
</div>

## Qualifications

- B.Sc.(Hons), University of Melbourne [(1988)]{.year-tag}
- Ph.D., University of Melbourne [(1992)]{.year-tag}
- A.Stat., Statistical Society of Australia [(2000)]{.year-tag}

## Employment history

- **Vice-Chancellor's Distinguished Professor**, Department of Econometrics & Business Statistics, Monash University [(2026--)]{.year-tag}
- **Professor**, Department of Econometrics & Business Statistics, Monash University [(2003--2026)]{.year-tag}
- **KNAW Visiting Professor**, TU/Eindhoven, Netherlands [(2016)]{.year-tag}
- **Visiting Senior Research Fellow**, Mathematical Sciences Institute, Australian National University [(2002)]{.year-tag}
- **Associate Professor**, Department of Econometrics & Business Statistics, Monash University [(2001--2003)]{.year-tag}
- **Senior Lecturer**, Department of Econometrics & Business Statistics, Monash University [(1998--2000)]{.year-tag}
- **Visiting Professor**, Department of Statistics, Colorado State University [(1998)]{.year-tag}
- **Senior Lecturer**, Department of Mathematics and Statistics, Monash University [(1997--1998)]{.year-tag}
- **Lecturer**, Department of Mathematics and Statistics, Monash University [(1995--1996)]{.year-tag}
- **Lecturer**, Department of Statistics, University of Melbourne [(1993--1994)]{.year-tag}
- **Statistical consultant**, Department of Statistics, University of Melbourne [(1985--1992)]{.year-tag}

## Fellowships

I am a fellow of the following organizations:

- [Australian Academy of Science](https://www.science.org.au/profile/rob-hyndman)
- [Academy of the Social Sciences in Australia](https://socialsciences.org.au/academy-fellow/?sId=0032v00003JxrvjAAB)
- [International Institute of Forecasters](https://forecasters.org/about/fellows/)

## Society memberships

- Elected member, [International Statistical Institute](https://www.isi-web.org)
- Member, [International Association for Statistical Computing](http://www.iasc-isi.org)
- Member, [International Association for Statistical Education](https://iase-web.org)
- Member, [International Society for Business and Industrial Statistics](http://isbis-isi.org)
- Member, [Statistical Society of Australia](http://www.statsoc.org.au)
- Member, [Foundation for Open Access Statistics](http://foastat.org/)

## Society leadership

- Director, [International Institute of Forecasters](https://forecasters.org/) [(2005--2018)]{.year-tag}
- Member, Scientific Program Advisory Group, [Statistical Society of Australia](http://www.statsoc.org.au) [(2001--2004)]{.year-tag}
- Central Council member, [Statistical Society of Australia](http://www.statsoc.org.au) [(1993--1996)]{.year-tag}
- Secretary, Victorian branch, [Statistical Society of Australia](http://www.statsoc.org.au) [(1993--1995)]{.year-tag}

## Academic and research leadership

- **Head**, Department of Econometrics & Business Statistics, Monash University
  [(2019--2022)]{.year-tag}
- **Director**, Business & Economic Forecasting Unit, Monash University
  [(2001--2017)]{.year-tag}
- **Director of Consulting**, Econometrics and Business Statistics, Monash University
  [(2000--2014)]{.year-tag}
- **Director**, Monash University Statistical Consulting Service [(1997--1998)]{.year-tag}
- **Director**, Key Centre for Statistical Science [(1996--1998)]{.year-tag}

## Editorial boards

- Executive Editor, *[The R Journal](https://rjournal.github.io)* [(2023--2026)]{.year-tag}
- Editor, *[Journal of Statistical Software](http://www.jstatsoft.org/)* [(2011--2025)]{.year-tag}
- Editor, [NEP forecasting report](http://ideas.repec.org/n/nep-for/) [(2005--2025)]{.year-tag}
- Editor-in-Chief, *[International Journal of Forecasting](http://ijf.forecasters.org/)* [(2005--2018)]{.year-tag}
- Associate Editor, *[International Journal of Forecasting](http://ijf.forecasters.org/)* [(2001--2004, 2019--)]{.year-tag}
- Theory and Methods Editor, *[Australian & New Zealand Journal of Statistics]()* [(2001--2004)]{.year-tag}

## Advisory boards

- Member of the Scaling committee, [Victorian Tertiary Admissions Centre](http://www.vtac.edu.au).
  This committee is responsible for producing the [ATAR for VCE students](http://en.wikipedia.org/wiki/Australian_Tertiary_Admission_Rank) [(1994--2025)]{.year-tag}
- Member of the ATAR Technical Group for the [Australasian Conference of Tertiary Admissions Centres](http://www.actac.edu.au) [(2003--2026)]{.year-tag}
- Member of the [National COVID-19 Epidemic Situational Assessment team](https://mspgh.unimelb.edu.au/research-groups/centre-for-epidemiology-and-biostatistics-research/infectious-disease-dynamics/national-covid-19-epidemic-situational-assessment-202023) [(2020--2023)]{.year-tag}
- Member of the Indigenous Statistical and Information Advisory Group for the [Australian Institute of Health and Welfare](http://www.aihw.gov.au) [(2017--2023)]{.year-tag}
- Member of the Methodology Advisory Committee for the Australian Bureau of Statistics [(2010--2018)]{.year-tag}

## Conference organization

- Chair, [IIF Workshop on Forecast Reconciliation](/prato2023/index.qmd) [(2023)]{.year-tag}
- Organizing committee, UserR! [(2018)]{.year-tag}
- Organizing committee, Shonan high-dimensional time series workshop [(2018)]{.year-tag}
- General Chair, International Symposium on Forecasting [(2017)]{.year-tag}
- Program Chair, International Symposium on Forecasting [(2012)]{.year-tag}
- Program Co-Chair, International Symposium on Forecasting [(2004)]{.year-tag}

## Awards and honours

- [Highly-Cited Researcher, Clarivate Analytics](https://www.webofscience.com/wos/author/record/A-2268-2008) [(2025)]{.year-tag}
- [The Australian Lead Researcher in Probability & Statistics with Application](https://www.monash.edu/news/articles/the-australian-names-monash-university-number-one-in-research-for-2024) [(2024)]{.year-tag}
- Australian Awards for University Teaching citation for outstanding contributions to student learning [(2022)]{.year-tag}
- [Pitman Medal, Statistical Society of Australia](https://www.statsoc.org.au/News-and-media-releases/10736720) [(2021)]{.year-tag}
- Vice-Chancellor's Award for Innovation in Learning and Teaching [(2021)]{.year-tag}
- MSA Teaching Excellence Award for Business and Economics, Monash Student Association [(2020)]{.year-tag}
- Dean's Award for Innovation in Learning and Teaching, Monash Business School [(2020)]{.year-tag}
- Commendation for the Dean's Award for Research Impact, Monash Business School [(2018)]{.year-tag}
- Nominee for MPA Supervisor of the Year, Monash Postgraduate Association [(2014)]{.year-tag}
- Dean's Award for Excellence in Innovation and External Collaboration, Monash Business School [(2010)]{.year-tag}
- HP Innovation Research Award [(2010)]{.year-tag}
- Dean's Award for Excellence in Research, Monash Business School [(2008)]{.year-tag}
- Vice-Chancellor's Award for Postgraduate Supervisor of the Year, Monash University [(2008)]{.year-tag}
- [Moran Medal for Statistical Science, Australian Academy of Science](https://www.science.org.au/past-winners/2007-awardees#moran) [(2007)]{.year-tag}
- Award for excellence in teaching, Monash Science Society [(1998)]{.year-tag}
- Finalist, Channel Ten Young Achiever Awards [(1990)]{.year-tag}
- Dwights Prize in Statistics, University of Melbourne [(1988)]{.year-tag}
- Norma McArthur Prize in Statistics, University of Melbourne [(1987)]{.year-tag}
- Second Maurice H Belz Prize in Statistics, University of Melbourne [(1986)]{.year-tag}

## In the news

Here is a list of [recent news articles about me](../news.qmd).

## Podcast interviews

{{< include /podcasts.qmd >}}

## Trivia

My [mathematical genealogy](/hyndsight/mathematical-genealogy/) goes back to Leibniz, Bernoulli, Euler, Lagrange and Poisson.

My [Erdös number](http://www.oakland.edu/enp/) is 3 in two different ways.

- via Peter Brockwell / Kai-Lai Chung / Paul Erdös
- via J.
  Keith Ord / Peter C Fishburn / Paul Erdös

## Other interests

- I play tennis for the [Heathmont Parker Reserve Tennis Club](http://www.hprtc.org.au/), and the [Ringwood Central Tennis Club](https://play.tennis.com.au/ringwoodcentraltennisclub)
- Previously I played cricket for the [Heathwood Cricket Club](https://www.heathwood.cc/).
  I'm also an accredited umpire with Cricket Australia

## Family websites

- [Leanne Hyndman](https://www.riverbankcounselling.com/)
- [Timothy Hyndman](https://timothyhyndman.com/)
- [Dave Hyndman](https://www.instagram.com/dave_hyndman/)
