---
title: "Ensemble forecasts of COVID-19 activity to support Australia's pandemic response: 2020-22"
date: "2026-04-22"
author:  Robert Moss, Ruarai J Tobin, Mitchell O'Hara-Wild, Adeshina I Adekunle, Dennis Liu, Tobin South, Dylan J Morris, Gerard E Ryan, Tianxiao Hao, Aarathy Babu, Katharine L Senior, James G Wood, Nick Golding, Joshua V Ross, Peter Dawson, Rob J Hyndman, David J Price, James M McCaw, Freya M Shearer
link: https://www.medrxiv.org/content/10.1101/2025.09.10.25335544v1
categories: Articles
details: "<i>PLOS Computational Biology</i>, <b>22</b>(4): e1014199"
doi: "10.1371/journal.pcbi.1014199"
---

During the COVID-19 pandemic, many countries used real-time data analyses, predictive modelling, and COVID-19 case forecasts, to incorporate emerging evidence into their decisions. In Australia, national and jurisdictional public health responses were informed by weekly ensemble forecasts of daily COVID-19 case counts for each of Australia’s eight states and territories, produced by a consortium of researchers under contract with the Australian Government. As members of this consortium, who produced these forecasts at each week, we now retrospectively evaluate approximately 100,000 predictions for daily case counts 1-28 days into the future, generated between July 2020 and December 2022, and report here (a) how the ensemble forecasts supported public health responses; (b) how well the ensemble forecast performed, relative to the forecasts produced by each contributing team; and (c) how we refined our reporting and visualisations to ensure that outputs were interpreted appropriately. Similar to COVID-19 forecasting studies in other countries, we found that the ensemble forecast consistently out-performed the individual model forecasts, and that performance was lowest when there were rapid changes in the epidemiology, such as periods around epidemic peaks. Our consortium’s internal peer-review process allowed us to explain how features of each ensemble forecast related to the design of the individual models, and this helped enable public health stakeholders to interpret the forecasts appropriately. Ultimately, our forecasts provided information that supported public health responses during periods of different policy goals, and over a wide range of epidemic scenarios.
