---
title: "Research team"
---

  * **Potential PhD students:** please read [Advice to PhD Applicants](/hyndsight/phdapplicants/)
  * **Potential research fellows:** All available positions are filled.

## Current PhD students

  1. **[Lakshan Bernard](https://acems.org.au/our-people/lakshan-bernard)**. *Analytical tools for future power networks* (PhD, begun 2020).
  1. **[Fan Cheng](https://fancheng.me/)**. *Manifold learning on empirical probability distributions* (PhD, begun 2019). [{{< fa brands github >}}](https://github.com/ffancheng) [{{< fa brands twitter >}}](https://twitter.com/fanchengfc)
  1. [**Daniele Girolimetto**](https://danigiro.github.io) *Advancements in probabilistic forecast reconciliation* (Visiting PhD student, 2022). [{{< fa brands github >}}](https://github.com/daniGiro)
  1. **Nuwani Palihawadana**. *Optimal predictor selection for high-dimensional nonparametric forecasting* (PhD, begun 2020).  [{{< fa brands github >}}](https://github.com/nuwani-palihawadana)
  1. **Sixian (Alice) Tang**. *Mortality forecasting* (PhD, begun 2020).
  1. **[Fin Yang](https://yangzhuoranyang.com/)**. *Forecast reconciliation with linear combinations* (PhD, begun 2020). [{{< fa brands github >}}](https://github.com/finyang/)

## Former research fellows

  1. **[Muhammad Akram](https://www.acu.edu.au/research-and-enterprise/our-research-institutes/mary-mackillop-institute-for-health-research/our-people/muhammad-akram)**
  1. **[George Athanasopoulos](https://research.monash.edu/en/persons/george-athanasopoulos)** [{{< fa brands github >}}](https://github.com/georgeAthana)
  1. **[Baki Billah](https://research.monash.edu/en/persons/md-billah)**
  1. **[Gary Deng](https://www.linkedin.com/in/gary-minfeng-deng)**
  1. **[Bircan Erbas](https://scholars.latrobe.edu.au/display/berbas)**
  1. **[Shu Fan](http://users.monash.edu.au/~shufan/)**
  1. **[Puwasala Gamakumara](https://puwasala.netlify.app/)** [{{< fa brands github >}}](https://github.com/PuwasalaG)
  1. **[Bin Jiang](https://www.linkedin.com/in/bin-jiang-44918b28/)**
  1. **[Sevvandi Kandanaarachchi](https://sevvandi.netlify.com/)** [{{< fa brands github >}}](https://github.com/sevvandi) [{{< fa brands twitter >}}](https://twitter.com/sevvandik)
  1. **[Yanfei Kang](http://yanfei.site)** [{{< fa brands github >}}](https://github.com/ykang) [{{< fa brands twitter >}}](https://twitter.com/yanfeikang)
  1. **[Stuart Lee](https://stuartlee.org/)** [{{< fa brands github >}}](https://github.com/sa-lee/) [{{< fa brands twitter >}}](https://twitter.com/_StuartLee)
  1. **[Zhuo Li](https://sites.google.com/view/zhuo-li/home)**
  1. **[Pablo Montero-Manso](https://www.sydney.edu.au/business/about/our-people/academic-staff/pablo-monteromanso.html)** [{{< fa brands github >}}](https://github.com/pmontman)
  1. **[Ingrida Steponavičė](http://users.monash.edu/~ingridas/)**
  1. **[Nick Tierney](https://www.njtierney.com/)** [{{< fa brands github >}}](https://github.com/njtierney) [{{< fa brands twitter >}}](https://twitter.com/nj_tierney)
  1. **[Shanika Wickramasuriya](https://unidirectory.auckland.ac.nz/people/profile/s-wickramasuriya)** [{{< fa brands github >}}](https://github.com/ShanikaLW)

## Former postgraduate students

  1. **[Roman Ahmed](https://www.linkedin.com/in/romanahmed)**. [*Forecasting hierarchical time series*](https://bridges.monash.edu/articles/thesis/Forecasting_hierarchical_time_series/14956233). (Ph.D., graduated 2010). Now a Data Scientist Consultant, Australian Taxation Office.
  1. **[Muhammad Akram](https://www.acu.edu.au/research-and-enterprise/our-research-institutes/mary-mackillop-institute-for-health-research/our-people/muhammad-akram)**. [*Stability properties of state space models for exponential smoothing*](https://bridges.monash.edu/articles/thesis/Stability_properties_of_state_space_models_for_exponential_smoothing/14873391), (Ph.D., graduated 2005). Now a Research Fellow at the ACU Mary MacKillop Institute for Health Research.
  1. **[Sengarapillai Arivalzahan](https://scholar.google.com/citations?user=jOoVou0AAAAJ)**. [*Discrimination and classification in functional data analysis*](https://bridges.monash.edu/articles/thesis/Discrimination_and_classification_in_functional_data_analysis/14971401), (Ph.D., graduated 2008). Now a Senior Lecturer at University of Jaffna, Sri Lanka.
  1. **[David Bashtannyk](https://www.linkedin.com/in/david-bashtannyk-53b30796)**. [*Kernel conditional density estimation*](https://bridges.monash.edu/articles/thesis/Kernel_conditional_density_estimation/14873652), (Ph.D., graduated 2001). Now Senior Manager  Valuations Risk at ANZ Bank.
  1. **[Souhaib Ben Taieb](http://souhaib-bentaieb.com/)**, *[Machine-learning strategies for multi-step time series forecasting](https://souhaib-bentaieb.com/papers/2014_phd.pdf)* (PhD, graduated 2014). Winner of a Solvay Award for his PhD thesis. Now Associate Professor at University of Mons. [{{< fa brands github >}}](https://github.com/bsouhaib/)
  1. **[Ashton de Silva](http://www.rmit.edu.au/contact/staff-contacts/academic-staff/d/de-silva-dr-ashton)**. [*The vector innovations structural time series framework*](https://bridges.monash.edu/articles/thesis/The_vector_innovations_structural_time_series_framework/14874258). (Ph.D., graduated 2007). Now an Associate Professor in the School of Economics, Finance and Marketing at RMIT.
  1. **[Alexander Dokumentov](https://www.linkedin.com/in/dokumentov/)**, *[Smoothing, decomposition and forecasting of multidimensional and functional time series using regularisation](https://bridges.monash.edu/articles/thesis/Smoothing_decomposition_and_forecasting_of_multidimensional_and_functional_time_series_using_regularisation/4713580)* (PhD, graduated 2016). Now a Data Scientist at Growing Data. [{{< fa brands github >}}](https://github.com/dokal01/)
  1. **[Bircan Erbas](https://scholars.latrobe.edu.au/display/berbas)**. *Statistical methodological issues in studies of respiratory disease and air pollution*, (Ph.D., Uni of Melbourne, graduated 2001). Now a Professor in the School of Public Health at La Trobe University.
  1. **[Puwasala Gamakumara](https://puwasala.netlify.app/)**, [*Probabilistic forecast reconciliation: theory and applications*](https://bridges.monash.edu/articles/thesis/Probabilistic_Forecast_Reconciliation_Theory_and_Applications/11869533) (PhD, graduated 2020).  Now a Senior Data Analyst at the Australian Energy Market Operator. [{{< fa brands github >}}](https://github.com/PuwasalaG)
  1. **[Sayani Gupta](https://sayani.netlify.com/)**. [*Visualization and analysis of probability distributions of deconstructed temporal data*](https://bridges.monash.edu/articles/thesis/Visualization_and_analysis_of_probability_distributions_of_large_temporal_data/19304453) (PhD, graduated 2022). Now an Analyst at the Australian Energy Market Operator. [{{< fa brands github >}}](https://github.com/Sayani07) [{{< fa brands twitter >}}](https://twitter.com/SayaniGupta07).
  1. **[Abdul Aziz Hayat](http://www.deakin.edu.au/about-deakin/people/abdul-hayat-muhammad)**. *[Identifying GDP volatility and modeling changing seasonality](https://bridges.monash.edu/articles/thesis/Identifying_GDP_volatility_and_modeling_changing_seasonality/14835549)*. (Ph.D., graduated 2007). Now a Senior Lecturer in the Deakin Business School.
  1. **[Atikur Khan](https://atikurkhan.net/)**. [*Some statistical aspects of singular spectrum analysis.*](https://bridges.monash.edu/articles/thesis/Some_statistical_aspects_of_singular_spectrum_analysis/4704922) (Ph.D., graduated 2013). Now an Associate Professor at North South University, Bangladesh.
  1. **[Yeasmin Khandakar](https://www.linkedin.com/in/yeasminkhandakar/)**. *[Automatic ARIMA forecasting](https://bridges.monash.edu/articles/thesis/Automatic_ARIMA_forecasting/14928636)*. (Ph.D., graduated 2010). Now a Senior Data Scientist at Transurban.
  1. **[Andrey Kostenko](https://www.linkedin.com/in/akoste01/)**. [*Statistical issues in modelling and forecasting sequential count data*](https://bridges.monash.edu/articles/thesis/Statistical_issues_in_modelling_and_forecasting_sequential_count_data/4628290). (Ph.D., graduated 2013). Now a Lead Data Scientist at Hydroinformatics Institute.
  1. **Hugh O'Reilly**. *[A comparison of trading strategies for share price index futures](https://bridges.monash.edu/articles/thesis/A_comparison_of_trading_strategies_for_share_price_index_futures/19548238)*. (M.Com., graduated 2004).
  1. **[Ahmad Farid Osman](https://umexpert.um.edu.my/faridosman)**. *[A new approach to forecasting based on exponential smoothing with independent regressors](https://bridges.monash.edu/articles/thesis/A_new_approach_to_forecasting_based_on_exponential_smoothing_with_independent_regressors/4649045)*. (Ph.D., graduated 2012). Now a Senior Lecturer at the University of Malaya.
  1. **Ivet Pitrun**. *[A smoothing spline approach to nonlinear inference for time series](https://bridges.monash.edu/articles/thesis/A_smoothing_spline_approach_to_nonlinear_inference_for_time_series/5466688)*, (Ph.D., graduated 2002). Now a teacher at [Monash College](http://www.monash.edu/monashcollege).
  1. **[Cameron Roach](https://www.linkedin.com/in/cameron-roach-00873b69/)**. *[Time series modelling and forecasting of disaggregated electricity data](https://bridges.monash.edu/articles/thesis/Time_series_modelling_and_forecasting_of_disaggregated_electricity_data/12671585)*, (PhD, graduated 2020). Now a Senior Data Analyst with the Department of Justice and Community Safety, Victoria. [{{< fa brands github >}}](https://github.com/camroach87/)
  1. **[Han Lin Shang](https://researchers.mq.edu.au/en/persons/hanlin-shang)**. *[Visualizing and forecasting functional time series](https://bridges.monash.edu/articles/thesis/Visualizing_and_forecasting_functional_time_series/4546333)*. (Ph.D., graduated 2010). Winner of Mollie Holman doctoral medal in Business &amp; Economics, 2010. Now a Professor at Macquarie University.
  1. **[Thilaksha Silva](https://www.linkedin.com/in/thilakshasilva/)**. *[Estimating and forecasting a time series of densities using a functional data approach](https://bridges.monash.edu/articles/thesis/Estimating_and_forecasting_a_time_series_of_densities_using_a_functional_data_approach/4679500)*. (PhD, graduated 2015). Now a Senior Data Scientist at CitiPower and Powercor.
  1. **Leanna Tedesco**. *Non-Gaussian first order autoregressive time series models*. (M.Sc., Uni of Melbourne, graduated 1995). Now Group Manager Forecasting, at [AEMO](https://aemo.com.au/en/about/careers/employee-stories/employee-in-the-spotlight-with-leanna-tedesco).
  1. **[Priyanga Dilini Talagala](http://prital.netlify.com/)**, [*Anomaly detection in streaming time series data*](https://bridges.monash.edu/articles/thesis/Anomaly_Detection_in_Streaming_Time_Series_Data/11302250) (PhD, graduated 2019). Now a Senior Lecturer at the University of Moratuwa, Sri Lanka. [{{< fa brands github >}}](https://github.com/pridiltal) [{{< fa brands twitter >}}](https://twitter.com/pridiltal)
  1. **[Thiyanga Talagala](https://thiyanga.netlify.com/)**, [*Computationally efficient forecasting methods for large-scale real-time applications*](https://bridges.monash.edu/articles/thesis/Computationally_Efficient_Forecasting_Methods_for_Large-Scale_Real-Time_Applications/10310507) (PhD, graduated 2019). Now a Senior Lecturer at the University of Sri Jayewardenepura, Sri Lanka. [{{< fa brands github >}}](https://github.com/thiyangt) [{{< fa brands twitter >}}](https://twitter.com/thiyangt)
  1. **[Shahid Ullah](https://www.flinders.edu.au/people/shahid.ullah)**. *[Demographic forecasting using functional data analysis](https://bridges.monash.edu/articles/thesis/Demographic_forecasting_using_functional_data_analysis/14876214)*. (Ph.D., graduated 2007). Now an Associate Professor in Biostatistics at Flinders University.
  1. **[Laura Villanova](https://scholar.google.com.au/citations?user=OeZdcD0AAAAJ)**. *Response surface optimization for high-dimensional systems with multiple responses*. (Ph.D., graduated 2010). Now working at the Technische Universität Graz, Austria.
  1. **[Earo Wang](http://earo.me)**, [*Tidy tools for supporting fluent workflow in temporal data analysis*](https://bridges.monash.edu/articles/thesis/Tidy_tools_for_supporting_fluent_workflow_in_temporal_data_analysis/11302226) (PhD, graduated 2019). Winner of Mollie Holman doctoral medal in Business &amp; Economics, 2019. Now a data scientist at Canva. [{{< fa brands github >}}](https://github.com/earowang) [{{< fa brands twitter >}}](https://twitter.com/earowang)
  1. **[Xiaozhe Catherine Wang (Lopes)](https://www.linkedin.com/in/catherine-lopes/)**. *[Characteristic-based forecasting for time series data](https://bridges.monash.edu/articles/thesis/Characteristic-based_forecasting_for_time_series_data/14973339)*, (Ph.D., graduated 2005). Winner of Mollie Holman doctoral medal in IT, 2005. Now Chief Data and Analytics Officer at ANZ bank.
  1. **[Shanika Wickramasuriya](https://unidirectory.auckland.ac.nz/people/profile/s-wickramasuriya)**. [*Optimal forecasts for hierarchical and grouped time series*](https://bridges.monash.edu/articles/thesis/Optimal_forecasts_for_hierarchical_and_grouped_time_series/5032136), (PhD, graduated 2017). Now a Lecturer at the University of Auckland. [{{< fa brands github >}}](https://github.com/ShanikaLW)
  1. **[Farah Yasmeen](https://www.researchgate.net/profile/Farah_Yasmeen)**. *[Functional linear models for mortality forecasting](https://bridges.monash.edu/articles/thesis/Functional_linear_models_for_mortality_forecasting/5044465)*. (Ph.D., graduated 2011). Now an Assistant Professor at the University of Karachi, Pakistan.
  1. **[Bruce Yu](https://www.linkedin.com/in/bruce-yu-198a3a10)**. *[Flood frequency analysis](https://bridges.monash.edu/articles/thesis/Flood_frequency_analysis/19574389)*. (M.Sc., graduated 1998). Now HR and Administration Manager at Generations Christian Education
